name: "Bug"
description: Template for reporting bugs.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "bug"
]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: "A detailed description of the bug."
      placeholder: "Describe the bug in detail..."
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behaviour:"
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
      
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what you expected to happen when following the steps above."
      
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: "A clear and concise description of what actually happened."
      placeholder: "Describe what actually happened instead of the expected behaviour."
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Attach images or drop them here."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Any other context about the problem, such as logs, code snippets, or links to relevant resources."
      placeholder: "Add any other context about the problem here."
