name: "Report Bug"
description: Create a report to help us reproduce and correct a bug.
title: "bug: <title>"
labels: [
  "bug", "needs-triage"
]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the problem
      description: |
        Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: |
        **Record steps to reproduce the bug as a video or GIF** (to eliminate ambiguity) and attach it here.
      
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
