name: "Bug"
description: Create a report to help us reproduce and correct a bug.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "bug"
]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: A detailed account of the issue, including what you observed versus what you expected to observe.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **Record steps to reproduce the bug as a video or GIF** (to eliminate ambiguity) and attach it here.

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Describe what you expected to happen when you followed the steps above.

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Describe what actually happened instead.
