name: "Epic"
description: A brief overview of the epic's overarching goal and its significance.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Clearly state the main objective of this epic. What are you aiming to achieve?
    validations:
      required: true

  - type: textarea
    id: background_context
    attributes:
      label: Background/Context
      description: Provide any relevant background information or context that led to the creation of this epic. Why is this epic important?

  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders
      description: Who are the main stakeholders? Who will benefit from this epic?
      
  - type: textarea
    id: acceptance_creteria
    attributes:
      label: Acceptance Criteria
      description: Define the criteria that, when met, will signify that the epic is complete. What are the success metrics?

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope
      description: Specify what is not included in this epic to set clear boundaries.

  - type: textarea
    id: features
    attributes:
      label: Features
      description: Provide a list or links to associated user stories or features that fall under this epic. This can be updated as new user stories or features are created.
