name: Feature Request
description: Template for proposing new features.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "feature"
]
body:
      
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: "A detailed description of the feature."
      placeholder: "Describe the feature and the value it adds..."
    validations:
      required: true

  - type: textarea
    id: background_context
    attributes:
      label: Background/Context
      description: Any relevant background information or context that led to the creation of this feature.

  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders
      description: Who are the main stakeholders? Who will benefit from this feature?
  
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: "If applicable, provide user stories to give context on how the feature will be used."
      placeholder: "As a [type of user], I want [an action or feature] so that [benefit/value]."
    validations:
      required: false
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "Criteria that must be met for the feature to be considered complete."
      placeholder: "- Criterion 1: [Description]\n- Criterion 2: [Description]\n- Criterion 3: [Description]\n- ..."
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: "Any additional information, context, or related issues."
      placeholder: "- Note 1: [Information]\n- Note 2: [Information]\n- ..."
    validations:
      required: false
      
  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: "Please select the type of feature this is."
      options:
        - label: New Functionality
          required: false
        - label: Improvement
          required: false
        - label: Performance Enhancement
          required: false
        - label: UI/UX
          required: false
        - label: Integration
          required: false
          
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "The priority of this feature."
      options:
        - Low
        - Medium
        - High
        - Urgent
    validations:
      required: true
      
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: "Links to any relevant documents, diagrams, or mock-ups."
      placeholder: "[Link 1], [Link 2], [Link 3]"
    validations:
      required: false
