name: "Feature Request"
description: Use this template for feature and enhancement proposals.
title: "[feat] "
projects: ["Perspicuity-Ltd/6"]
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a detailed description of the new feature, including its purpose and objectives. Be sure to explain how the feature will benefit the user and provide any necessary background information.
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: |
        Detail different scenarios in which the new feature will be used. This should include how users will interact with the feature and how it fits into the overall functionality of Percy.
    validations:
      required: false

  - type: textarea
    id: acceptance_creteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define the specific criteria that need to be met in order for the feature to be considered complete. This should include both functional and non-functional requirements, such as performance metrics and security requirements.
    validations:
      required: true

  - type: textarea
    id: impact_analysis
    attributes:
      label: Impact Analysis
      description: |
        Assess the potential impact of the new feature on existing code and functionality. This should include any potential conflicts or risks that need to be addressed.
    validations:
      required: false
