name: "Story"
description: This template is designed to capture the requirements for both user-facing and technical work.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "story"
]
body:
  - type: markdown
    attributes:
      value: "## User Story and Technical Story Template\nThis template is designed to capture the requirements for both user-facing and technical work. Please select the appropriate type of story and fill in the details accordingly."
  
  - type: dropdown
    id: story-type
    attributes:
      label: Type
      description: "Select the type of story."
      options:
        - User Story
        - Technical Story
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"
      
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: "Format: As a [type of user], I want [an action or feature] so that [benefit/value]."
      placeholder: "As a [type of user], I want [an action or feature] so that [benefit/value]."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: technical-story
    attributes:
      label: Technical Story
      description: "Describe the technical objective and requirements."
      placeholder: "Objective: [Clear, concise statement of the goal]\n\nTechnical Requirements:\n- Requirement 1: [Description]\n- Requirement 2: [Description]\n- Requirement 3: [Description]\n- ...\n\nRationale: [Explanation of how this supports the system, architecture, or future development]"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the criteria to meet to consider this story complete."
      placeholder: "- Criterion 1: [Description]\n- Criterion 2: [Description]\n- Criterion 3: [Description]\n- ..."
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: "Add any additional notes, information, or context for the story here."
      placeholder: "- Note 1: [Information]\n- Note 2: [Information]\n- ..."
    validations:
      required: false
