name: "User Story"
description: A brief summary of the user story.
projects: ["Perspicuity-Ltd/6"]
body:
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      placeholder: |
        As a <actor>,
        I want to <action>,
        So that <benefit>
    validations:
      required: true
      
  - type: textarea
    id: acceptance_creteria
    attributes:
      label: Acceptance Criteria
      description: |
        List the criteria that, when met, will signify that the user story is complete.
    validations:
      required: true
