name: Issue
description: Template for creating new issues.
projects: ["Perspicuity-Ltd/6"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Description
      description: "A detailed description of the task."
      placeholder: "Describe the task in detail..."
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "Criteria that must be met for the task to be considered complete."
      placeholder: "- Criterion 1: [Description]\n- Criterion 2: [Description]\n- Criterion 3: [Description]\n- ..."
    validations:
      required: true
      
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: "Any additional information, context, or related issues."
      placeholder: "- Note 1: [Information]\n- Note 2: [Information]\n- ..."
    validations:
      required: false
      
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: "Links to any relevant documents, diagrams, or mock-ups."
      placeholder: "[Link 1], [Link 2], [Link 3]"
    validations:
      required: false
