name: Task
description: A concise summary of the task detailing what needs to be done.
projects: ["Perspicuity-Ltd/6"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Provide a concise and clear summary of the task.
        
  - type: textarea
    id: acceptance_creteria
    attributes:
      label: Acceptance Criteria
      description: Specific conditions that must be met for the task to be considered complete.
    validations:
      required: true
