name: Technical Story
description: Template for creating technical stories.
title: ""
projects: ["Perspicuity-Ltd/6"]
labels: [
  "story"
]

body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: "What is the goal of this technical story?"
      placeholder: "Enter the goal of the technical story here."
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: "What are the specific technical requirements?"
      placeholder: "List the specific technical requirements here, such as tasks to be completed, features to be added, or systems to be improved."
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: "Why is this work important? How does it support the system, architecture, or future development?"
      placeholder: "Explain the importance of this work and how it contributes to the overall system or objectives."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the criteria to meet to consider this technical story complete."
      placeholder: "Define clear and measurable criteria that must be met for this technical story to be considered complete."
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: "Add any additional notes, information, or context for the story here."
      placeholder: "Include any additional information that may be helpful for understanding the context or details of the story."
    validations:
      required: false
