name: Report Bug (UI)
description: Create a report to help us reproduce and correct a UI bug.
labels: ["bug"]
title: "<title>"

body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the problem
      description: |
        Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: |
        **Record steps to reproduce the bug as a video or GIF** (to eliminate ambiguity) and attach it here.

  - type: textarea
    attributes:
      label: Is the console panel in DevTools showing errors relevant to the bug?
      description: |
        If the console panel in your browser's DevTools is showing errors (displayed in red) relevant to the bug as shown in the screenshot below, please provide them as text (preferred) or a screenshot.

        #### Instructions on how to use DevTools:
        - Chrome: [Chrome DevTools](https://developer.chrome.com/docs/devtools/)
        - Firefox: [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html)
        - Edge: [Overview of DevTools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview)

        ![console-panel](https://github.com/Perspicuity-Ltd/.github/blob/main/.github/ISSUE_TEMPLATE/images/console-panel.png?raw=true)
        <p align="center">Console panel on Chrome</P>
      placeholder: |
        ```
        TypeError: Cannot read properties of null (reading 'map')
          at Nf (forum-web-part.js:2:1055977)
          at Yr (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:64000)
          at ys (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:109887)
          at pc (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:102665)
          at uc (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:102590)
          at ac (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:99620)
          at react-dom-16-bundle_none_c677b08c440c9638b562.js:2:51414
          at t.unstable_runWithPriority (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:5230)
          at Gi (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:51124)
          at Qi (react-dom-16-bundle_none_c677b08c440c9638b562.js:2:51360)
        ```

  - type: textarea
    attributes:
      label: Does the network panel in DevTools contain failed requests relevant to the bug?
      description: |
        If the network panel in your browser's DevTools contain failed requests (displayed in red) relevant to the bug as shown in the screenshot below, please provide them as text (preferred) or a screenshot.

        ![network-panel](https://github.com/Perspicuity-Ltd/.github/blob/main/.github/ISSUE_TEMPLATE/images/network-panel.png?raw=true)
        <p align="center">Network panel on Chrome</P>
      placeholder: |
        ```
        # Request URL
        https://pnptelemetryproxy.azurewebsites.net/track

        # Status Code
        400

        # Payload
        [{"name":"ReactWebPartTitle","properties":{"version":"3.12.0","controlType":"react","debug":"false","environment":"SharePoint","title":true,"updateProperty":true,"className":false}}]

        # Response
        Failed to load response data. No data found for resource with given identifier
        ```
