name: User Story
description: Template for creating user stories.
projects: ["Perspicuity-Ltd/6"]
labels: [
  "story"
]
body:
  - type: textarea
    id: story
    attributes:
      label: Story/Objective
      description: "Format: As a [type of user], I want [an action or feature] so that [benefit/value]."
      placeholder: "As a [type of user], I want [an action or feature] so that [benefit/value]."
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the criteria to meet to consider this story complete."
      placeholder: "- Criterion 1: [Description]\n- Criterion 2: [Description]\n- Criterion 3: [Description]\n- ..."
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: "Add any additional notes, information, or context for the story here."
      placeholder: "- Note 1: [Information]\n- Note 2: [Information]\n- ..."
